src/App.reducer.js, src/index.js
Added the top level integration for redux, this involves:
- making a store for the data
- adding a high level reducer
- integrating redux-thunk to allow async updates of the state store
connected to #8
=> Added the top level store and reducer for using redux

package-lock.json, package.json, src/App.routes.js, src/index.js
Added in react router and hooked the history in to the redux state so we can later hook up time-travel debugging.
Currently there is a high level router component which we can expand later to add more routes if needed.
Waffle integration:
connect to #9
=> Added a top level router and hooked the history into the redux state

.gitignore, .travis.yml, continuous_integration/package_artifacts.sh, package-lock.json, package.json, src/App.css
Added in a travis script that checks the code quality, builds the code, runs the tests and then deploys if it is a tagged commit.
We also upload the coverage statistics to codecov.
connect to #16
connect to #18
=> Feature/travis build #16

.travis.yml, server/canned_data/Sub/request_TTLIN-meta, server/canned_data/Sub/response_TTLIN-meta
Canned data for request & response messages for TTLIN block meta
Also changed travis key to one for "dls-controls-user"
connect to #22 
connect to #36
=> TTLIN canned data (+ changed travis key)

demos/sprint0/20-dev-malcolm-server.md, demos/sprint0/21+15-smg.md, demos/sprint0/27-parent-child-drawers.md, demos/sprint0/setting-up-dev-environment.md, package-lock.json, package.json, src/index.js
Added demos for other sprint0 stories.
Added an offline version of the Roboto font
Integrated in the Redux dev tools.
=> Added more demos and integrated the redux dev tools

server/canned_data/Sub/request_INENC, server/canned_data/Sub/request_PANDA-layout, server/canned_data/Sub/request_PANDA-meta, server/canned_data/Sub/request_SEQ, server/canned_data/Sub/request_SEQ-meta, server/canned_data/Sub/response_INENC, server/canned_data/Sub/response_PANDA-layout, server/canned_data/Sub/response_PANDA-meta, server/canned_data/Sub/response_SEQ, server/canned_data/Sub/response_SEQ-meta, server/canned_data/Sub/response_TTLIN
=> Added more canned data

demos/sprint0/interactive_socket.js, package.json, server/test-malcolm-server.js, src/blockDetails/__snapshots__/blockDetails.test.js.snap, src/blockDetails/blockDetails.component.js, src/blockDetails/blockDetails.stories.js, src/blockDetails/blockDetails.test.js, src/blockDetails/fieldsLoading/__snapshots__/fieldsLoading.test.js.snap, src/blockDetails/fieldsLoading/fieldsLoading.component.js, src/blockDetails/fieldsLoading/fieldsLoading.stories.js, src/blockDetails/fieldsLoading/fieldsLoading.test.js, src/malcolm/malcolm.types.js, src/malcolm/malcolmHandlers/attributeHandler.js, src/malcolm/malcolmHandlers/attributeHandler.test.js, src/malcolm/malcolmHandlers/blockMetaHandler.js, src/malcolm/malcolmHandlers/blockMetaHandler.test.js, src/malcolm/malcolmReducer.js, src/malcolm/malcolmReducer.test.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/malcolmSocketHandler.test.js
Hooked up subscribing to attributes once a meta response is received.
Added a control to show the attributes loading.
Updated the test socket server to have a random element to the delay to better simulate a real environment.
Added tests to go with all new functionality.
connect to #42
=> Feature/subscribe toattribute data #42

src/index.js, src/malcolm/malcolmReducer.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/malcolmSocketHandler.test.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.component.js, src/malcolmWidgets/checkbox/checkbox.component.js
=> Feature/malcolm put #46

src/blockDetails/blockDetails.stories.js, src/blockDetails/fieldsLoading/fieldsLoading.stories.js, src/drawerContainer/drawerHeader.stories.js, src/malcolm/middleware/malcolmReduxMiddleware.js, src/malcolm/middleware/malcolmReduxMiddleware.test.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolm/reducer/navigation.reducer.js, src/malcolm/reducer/navigation.reducer.test.js, src/malcolmWidgets/attributeDetails/attributeDetails.stories.js, src/malcolmWidgets/checkbox/checkbox.stories.js, src/malcolmWidgets/comboBox/comboBox.stories.js, src/malcolmWidgets/groupExpander/groupExpander.stories.js, src/malcolmWidgets/led/widgetLED.stories.js, src/malcolmWidgets/textUpdate/WidgetTextUpdate.stories.js, src/navbar/__snapshots__/navbar.test.js.snap, src/navbar/__snapshots__/navcontrol.test.js.snap, src/navbar/navbar.component.js, src/navbar/navbar.selector.js, src/navbar/navcontrol.component.js, src/navbar/navcontrol.test.js
Hooked up the drop downs so you can navigate to different blocks.
- Review code
- run `npm start` and navigate to http://localhost:3000/gui/ and select a block from the drop down in the nav bar.
connect to #87
=> Feature/hook up nav bar #87

server/loadCannedData.js, server/test-malcolm-server.js, src/index.js, src/malcolm/malcolmActionCreators.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/malcolmSocketHandler.test.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.component.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.test.js
Improved dev server so it now responds to Put messages with a delta containing the updated value (if subscribed) and a return.
- Review code
- npm run
- navigate to gui/PANDA:INENC1 (or any page with a combobox/checkbox) and try changing a value
connect to #100
=> Feature/dev server put #100

docs/source/SMG/setting_up_a_dev_environment.rst, docs/source/conf.py, docs/source/requirements.txt, src/blockDetails/blockDetails.component.js, src/layout/block/__snapshots__/blockWidget.component.test.js.snap, src/layout/block/blockWidget.component.js, src/mainMalcolmView/__snapshots__/middlePanel.container.test.js.snap, src/mainMalcolmView/mainMalcolmView.container.js, src/mainMalcolmView/middlePanel.container.js
Various sprint review fixes
- fix label in group expander
- fix popout size in Chrome
- added a virtual env set up for building the docs
- Review code
- Pay particular attention to the virtualenv instructions, do these work on a diamond system?
=> Feature/layout model #94

package.json, src/layout/blockPort/blockPort.model.test.js, src/layout/link/__snapshots__/link.factory.test.js.snap, src/layout/link/link.factory.test.js, src/layout/link/splineUtils.test.js, src/malcolm/blockUtils.js, src/malcolm/blockUtils.test.js, src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/layout.reducer.js, src/malcolm/reducer/layout.reducer.test.js
Cleaned up some of the reducers and added more test coverage
- Review code
connect to #130 
connect to #128
=> Feature/fix link position #128

src/blockDetails/blockDetails.component.js, src/drawerContainer/drawerContainer.component.js, src/drawerContainer/drawerContainer.test.js, src/malcolm/middleware/malcolmRouting.js, src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolm/reducer/navigation.reducer.js, src/malcolm/reducer/navigation.reducer.test.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.component.js, src/malcolmWidgets/textInput/WidgetTextInput.component.js, src/navbar/__snapshots__/navbar.test.js.snap, src/navbar/__snapshots__/navcontrol.test.js.snap, src/navbar/navbar.component.js, src/navbar/navbar.test.js, src/navbar/navcontrol.component.js, src/viewState/viewState.actions.js, src/viewState/viewState.actions.test.js, src/viewState/viewState.reducer.js, src/viewState/viewState.reducer.test.js
Added an extra nav dropdown at the end to allow children to be selected.
- Review code
connect to #135
=> Feature/extra nav drop down #135

server/test-malcolm-server.js, src/layout/block/block.model.js, src/layout/block/block.stories.js, src/layout/block/blockWidget.component.js, src/mainMalcolmView/__snapshots__/middlePanel.container.test.js.snap, src/mainMalcolmView/middlePanel.container.js, src/mainMalcolmView/middlePanel.container.test.js, src/malcolm/malcolmActionCreators.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/navigation.reducer.js, src/malcolm/reducer/navigation.reducer.test.js, src/navbar/__snapshots__/navbar.test.js.snap, src/navbar/navbar.test.js, src/navbar/navcontrol.component.js, src/navbar/navcontrol.test.js
Updated the UI to send position changes back to the server.
Also updated the nav menu to use the names from the layout attribute
- Review code
connect to #129 
connect to #127
=> Feature/update block position #129

server/pyScripts/canned_data_generator.py, src/layout/layout.component.js, src/malcolm/reducer/layout.reducer.js
Updated the layout component so it adds existing links from the model.
- Review code
connect to #133
=> Updated the layout component so it displays existing links

src/blockDetails/blockDetails.test.js, src/malcolm/actions/method.actions.js, src/malcolm/actions/method.actions.test.js, src/malcolm/malcolmActionCreators.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolm/reducer/method.reducer.test.js, src/malcolmWidgets/method/__snapshots__/method.component.test.js.snap, src/malcolmWidgets/method/method.component.js, src/malcolmWidgets/method/method.component.test.js
Added extra tests for the functionality in the last pull request
- Review code
connect to #167 
connect to #168
=> Added extra tests for the method inputs

src/Snackbar/snackbar.component.js, src/Snackbar/snackbar.test.js, src/malcolm/malcolm.types.js, src/malcolm/malcolmActionCreators.js, src/malcolm/malcolmActionCreators.test.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/malcolmSocketHandler.test.js, src/malcolm/middleware/malcolmReduxMiddleware.js, src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolmWidgets/table/__snapshots__/table.component.test.js.snap, src/viewState/viewState.actions.js, src/viewState/viewState.reducer.js, src/viewState/viewState.reducer.test.js
Refactored messagesInFlight to be an object, keyed by whatever the malcolm message ID is (typically an int). Also moved snackbar from malcolm state to view state.
- Review code
- npm test
connect to #199 
connect to #202
=> Feature/reducer refactor #199

src/malcolm/malcolmHandlers/attributeHandler.js, src/malcolm/malcolmHandlers/attributeHandler.test.js, src/malcolm/malcolmHandlers/layoutHandler.js, src/malcolm/malcolmHandlers/layoutHandler.test.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/middleware/malcolmRouting.js, src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/malcolmReducer.js
Removed treatment of 'layout' attribute as a special case, instead looking for 'widget:flowgraph' tag
- Review code
- npm test
connect to #203
=> Feature/refactor layout #203

src/layout/layout.component.js, src/layout/layout.test.js, src/malcolm/NavTypes.js, src/malcolm/actions/navigation.actions.js, src/malcolm/actions/navigation.actions.test.js, src/malcolm/malcolmHandlers/attributeHandler.js, src/malcolm/malcolmHandlers/attributeHandler.test.js, src/malcolm/malcolmHandlers/blockMetaHandler.js, src/malcolm/malcolmHandlers/layoutHandler.js, src/malcolm/malcolmHandlers/layoutHandler.test.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/malcolmSocketHandler.test.js, src/malcolm/middleware/malcolmReduxMiddleware.js, src/malcolm/middleware/malcolmReduxMiddleware.test.js, src/malcolm/middleware/malcolmRouting.js, src/malcolm/middleware/malcolmRouting.test.js, src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolm/reducer/navigation.reducer.js, src/malcolm/reducer/navigation.reducer.test.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.component.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.test.js
Updated all the url handling so it now works with a tree of objects. Various updates throughout the code to get the nav elements to populate.
- Review code
- Run the website and navigate to `/gui/PANDA/layout/SEQ2/table/.info`
connect to #206 
closes #206
=> Feature/refactor url handling #206

docs/source/conf.py, src/drawerContainer/drawerContainer.component.js, src/drawerContainer/drawerContainer.test.js, src/layout/layout.component.js, src/layout/layout.test.js, src/malcolm/actions/navigation.actions.js, src/malcolm/actions/navigation.actions.test.js, src/viewState/viewState.actions.js, src/viewState/viewState.actions.test.js
Removed keying on layout from viewState actions and moved corresponding actions into navigation actions. Also changed copyright information in docs
- Review code
- npm test
connect to #200 
closes #200
=> Removed keying on layout from viewState actions

src/blockDetails/__snapshots__/blockDetails.test.js.snap, src/blockDetails/blockDetails.component.js, src/index.js, src/malcolmWidgets/attributeDetails/attributeSelector/__snapshots__/attributeSelector.test.js.snap, src/malcolmWidgets/buttonAction/__snapshots__/buttonAction.test.js.snap, src/malcolmWidgets/buttonAction/buttonAction.component.js, src/malcolmWidgets/groupExpander/groupExpander.component.js, src/malcolmWidgets/method/__snapshots__/method.component.test.js.snap, src/malcolmWidgets/method/method.component.js, src/malcolmWidgets/table/table.component.test.js, src/malcolmWidgets/textUpdate/WidgetTextUpdate.component.js, src/malcolmWidgets/textUpdate/WidgetTextUpdate.test.js
Various style updates that came out of the style review
- Review code
- Run the site and check against the style updates list in Slack
connect to #268
=> Feature/style updates #268

public/index.html, src/layout/block/__snapshots__/blockWidget.component.test.js.snap, src/layout/block/blockWidget.component.js, src/layout/layout.component.js, src/layout/layout.test.js, src/layout/link/link.model.test.js, src/layout/link/splineUtils.js, src/layout/link/splineUtils.test.js
Fixed the loop back spline on Firefox. Fixed the curvature to match master as well as introduce a vertical dependency. Also fixed the bin only appearing on drag (note this had to be done by setting a timeout that gets cancelled on mouseUp).
- Review code
- Run the site and play with the blocks on the layout
connect to #277
=> Fixed various issues with the splines

package-lock.json, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/navigation.reducer.js, src/navbar/__snapshots__/navbar.test.js.snap, src/navbar/__snapshots__/navcontrol.test.js.snap, src/navbar/navbar.component.js, src/navbar/navbar.test.js, src/navbar/navcontrol.component.js, src/navbar/navcontrol.test.js
Changed navbar so dropdown appears to the right of the element and three dots appear to select a new child (if the last element has any). Required some tweaks to the navigation reducer so each nav element now tracks its parent.
- Review code
- npm start
- navigate to localhost:3000/gui
- use the navbar to navigate around
connect to #335 
closes #335
=> Feature/nav bar tweak #335

package-lock.json, src/layout/layout.component.js, src/malcolm/malcolm.types.js, src/malcolm/malcolmActionCreators.js, src/malcolm/reducer/layout/layout.reducer.js, src/malcolm/reducer/layout/layout.reducer.test.js, src/malcolm/reducer/layout/layoutEngine.helper.js, src/malcolm/reducer/layout/layoutEngine.helper.test.js, src/malcolm/reducer/malcolmReducer.js
Started tracking selected links and updated that on the layout engine when it gets rebuilt.
- Review code
- Start the site, go to the layout and select a link, see that the link is still selected when the child window opens.
connect to #328 
closes #328
=> Feature/keep links selected #328

src/blockDetails/__snapshots__/blockDetails.test.js.snap, src/blockDetails/blockDetails.component.js, src/infoDetails/infoBuilders.js, src/malcolmWidgets/attributeDetails/attributeDetails.component.js, src/malcolmWidgets/attributeDetails/attributeSelector/__snapshots__/attributeSelector.test.js.snap, src/malcolmWidgets/checkbox/checkbox.component.js, src/malcolmWidgets/comboBox/__snapshots__/comboBox.test.js.snap, src/malcolmWidgets/comboBox/comboBox.component.js, src/malcolmWidgets/groupExpander/__snapshots__/groupsExpander.test.js.snap, src/malcolmWidgets/groupExpander/groupExpander.component.js, src/malcolmWidgets/led/widgetLED.component.js, src/malcolmWidgets/method/method.component.js
Fixed various style changes referenced in #324 
- Review code
- Start the site and go through the changes listed in #324 to check them.
connect to #324 
closes #324
=> Feature/style updates #324

cypress/integration/malcolmjs_spec.js, demos/sprint9/layout-updates.md, demos/sprint9/overview.md, demos/sprint9/prepare-for-panda.md, demos/sprint9/ray-style-updates.md, settings.dev.json, settings.prod.json, src/blockDetails/__snapshots__/blockDetails.test.js.snap, src/blockDetails/blockDetails.component.js, src/blockDetails/blockDetails.test.js, src/infoDetails/infoBuilders.js, src/infoDetails/infoDetails.component.js, src/layout/layout.component.js, src/mainMalcolmView/__snapshots__/middlePanel.container.test.js.snap, src/mainMalcolmView/middlePanel.container.js, src/malcolm/reducer/layout/layoutEngine.helper.js
Various style changes after the sprint review
- Review code
- {more steps here}
=> Feature/style updates part2 #325

.travis.yml, src/layout/block/__snapshots__/blockWidget.component.test.js.snap, src/layout/block/blockWidget.component.js, src/layout/blockPort/__snapshots__/blockPortWidget.test.js.snap, src/layout/blockPort/blockPortWidget.component.js, src/layout/blockPort/blockPortWidget.test.js, src/layout/layout.component.js, src/malcolm/actions/layout.action.js
Increased the drop zone as well as added a highlight for the drop zone when the port is the right type.
- Review code
- Run the site and see that you can pick up or drop a link within a wider area. See also that there is a drop highlight for sink ports of the same type if starting from a source port.
connect to #331 
connect to #338 
closes #331 
closes #338
=> Increased the port drop zone size as well as added a highlight for it

sonar-project.properties, src/infoDetails/infoBuilders.test.js, src/infoDetails/infoElement.component.test.js, src/layout/blockPort/blockPortWidget.component.js, src/layout/layout.test.js, src/malcolm/malcolmHandlers/attributeHandler.js, src/malcolm/malcolmSocketHandler.test.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolmWidgets/attributeDetails/attributeDetails.component.js, src/malcolmWidgets/attributeDetails/attributeDetails.test.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.component.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.test.js, src/malcolmWidgets/table/table.container.js, src/malcolmWidgets/table/table.container.test.js, src/middlePanelViews/methodView/methodViewer.component.test.js, src/middlePanelViews/plotter.component.test.js
- Removed potential bugs identified by sonarqube, 
- fixed the major code smells (still a lot of renaming ones that aren't important)
- fixed a lot of duplication in tests
- Review code
- Check the site still runs as it did before the refactor
connect to #208 
closes #208
=> Feature/fix sonar issues #208

package-lock.json, package.json, src/Snackbar/__snapshots__/snackbar.test.js.snap, src/blockDetails/fieldsLoading/__snapshots__/fieldsLoading.test.js.snap, src/drawerContainer/__snapshots__/drawerHeader.test.js.snap, src/layout/__snapshots__/layoutBin.component.test.js.snap, src/layout/block/__snapshots__/BlockNodeFactory.test.js.snap, src/mainMalcolmView/__snapshots__/middlePanel.container.test.js.snap, src/malcolmWidgets/attributeDetails/attributeAlarm/__snapshots__/attributeAlarm.test.js.snap, src/malcolmWidgets/attributeDetails/attributeAlarm/attributeAlarm.component.js, src/malcolmWidgets/attributeDetails/attributeSelector/__snapshots__/attributeSelector.test.js.snap, src/malcolmWidgets/comboBox/__snapshots__/comboBox.test.js.snap, src/malcolmWidgets/groupExpander/__snapshots__/groupsExpander.test.js.snap, src/malcolmWidgets/method/__snapshots__/method.component.test.js.snap, src/malcolmWidgets/table/__snapshots__/table.component.test.js.snap, src/malcolmWidgets/table/__snapshots__/virtualizedTable.component.test.js.snap, src/malcolmWidgets/textInput/__snapshots__/WidgetTextInput.test.js.snap, src/navbar/__snapshots__/navbar.test.js.snap, src/navbar/__snapshots__/navcontrol.test.js.snap
Updated MaterialUI to v3. Also changed disconnected alarm icon to "power_off" material icon (this was not available in the previous version of material UI)
- Review code
- npm run:ui-only and npm run:server (in a separate window)
- navigate to localhost:3000/PANDA
- wait til the site is loaded, then kill the dev server process.
- view the new disconnected icon
=> Updated MaterialUI to v3

src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/malcolm/reducer/block.reducer.js, src/malcolm/reducer/malcolmReducer.js, src/malcolm/reducer/malcolmReducer.test.js, src/malcolm/reducer/socket.reducer.js, src/malcolm/reducer/socket.reducer.test.js, src/malcolmWidgets/attributeDetails/attributeDetails.component.js
Refactored malcolm reducer
- Review code
- npm test
- check everything passes
connect to #207 
closes #207
=> Feature/malcolm reducer refactor #207

demos/sprint10/bug-fixes.md, demos/sprint10/child-panel.md, demos/sprint10/code-quality.md, demos/sprint10/overview.md, demos/sprint10/port-target.md, server/subscriptionFeed.js, src/index.css, src/layout/block/blockWidget.component.js, src/layout/blockPort/blockPortWidget.component.js, src/layout/link/__snapshots__/link.factory.test.js.snap, src/layout/link/autoLinkSegment.js, src/layout/link/link.factory.js, src/mainMalcolmView/__snapshots__/middlePanel.container.test.js.snap, src/mainMalcolmView/middlePanel.container.js, src/malcolm/actions/navigation.actions.js, src/malcolm/actions/navigation.actions.test.js, src/malcolm/reducer/attribute.reducer.js, src/malcolm/reducer/attribute.reducer.test.js, src/middlePanelViews/__snapshots__/plotter.component.test.js.snap, src/middlePanelViews/attributeView/__snapshots__/attributeView.container.test.js.snap, src/middlePanelViews/attributeView/archiveTable.container.js, src/middlePanelViews/attributeView/archiveTable.container.test.js, src/middlePanelViews/attributeView/attributeView.container.js, src/middlePanelViews/methodView/__snapshots__/methodArchive.test.js.snap, src/middlePanelViews/methodView/methodArchive.test.js, src/middlePanelViews/plotter.component.js, src/middlePanelViews/plotter.component.test.js, src/middlePanelViews/tabbedMiddlePanel.component.js, src/testState.utilities.js
Fixed the rendering of the nav bar during fast attribute updates.
Fixed various items from the sprint 10 reivew
- Review code
- View the graph for a fast updating attribute
=> Feature/fast update graph perf #317

src/layout/layout.component.js, src/mainMalcolmView/middlePanel.container.js, src/malcolm/actions/method.actions.js, src/malcolm/actions/method.actions.test.js, src/malcolm/malcolmActionCreators.js, src/malcolm/reducer/method.reducer.js, src/malcolmWidgets/attributeDetails/attributeSelector/attributeSelector.component.js, src/malcolmWidgets/method/__snapshots__/method.component.test.js.snap, src/malcolmWidgets/method/method.component.js, src/malcolmWidgets/method/method.component.test.js, src/middlePanelViews/methodView/methodViewer.component.js, src/middlePanelViews/methodView/methodViewer.component.test.js
Added validation of required method parameters; if one attempts to run a method whilst some of the required inputs have no defined value, the Post will not be sent and the offending parameter(s) will be flagged with a warning alarm icon.
- Review code
- npm run ui-only
- connect to a malcolm instance which has some methods
- Click on the info for a parameter which is required (these should initialise with a pencil icon next to them); alternatively click the overall info for a method which has such a parameter
- Click the discard parameter button and check the pencil icon disappears
- Click the button to run the method
- Check that the required parameter(s) is …
=> Feature/method validation #211

cypress/integration/child_panel_state_spec.js, src/infoDetails/infoBuilders.js, src/mainMalcolmView/__snapshots__/middlePanel.container.test.js.snap, src/mainMalcolmView/middlePanel.container.js, src/malcolm/actions/layout.action.js, src/malcolm/malcolm.types.js, src/malcolm/reducer/layout/layout.reducer.js, src/malcolm/reducer/layout/layout.reducer.test.js
Added zoom buttons to layout
- Review code
- npm start
- navigate to localhost:3000/gui/PANDA/layout
- try zooming with the buttons
connect to #278 
closes #278
=> Added zoom buttons to layout

package-lock.json, src/malcolm/malcolmActionCreators.js, src/malcolm/malcolmHandlers/blockMetaHandler.js, src/malcolm/malcolmHandlers/blockMetaHandler.test.js, src/malcolm/malcolmSocketHandler.js, src/malcolm/middleware/malcolmReduxMiddleware.js, src/malcolm/middleware/malcolmRouting.js, src/malcolm/reducer/block.reducer.js, src/malcolm/reducer/layout/layout.reducer.js, src/malcolm/reducer/malcolmReducer.js
Fixed bug where blocks on the layout were not updating and/or getting stuck as loading on a label update
- Review code
- npm run ui-only
- edit public/settings.json to connect to a pymalcolm instance
- navigate to the layout
- select a block from the layout and edit its label in the child pane
- check that the label update is applied to the block on the layout and that the block doesnt get stuck in loading
connect to #427 
closes #427
=> Bugfix/block updates #427

src/index.js, src/navbar/__snapshots__/navcontrol.test.js.snap, src/navbar/navcontrol.component.js
Current item in dropdown nav menu is now selected. Also added new port type tag & colour for "block"
- Review code
- npm start
- navigate to localhost:3000/gui/PANDA/layout/TTLIN1
- click on the nav drop down next to TTLIN1
- check that TTLIN1 is selected in the nav menu and that the view scrolls to it
connect to #420 
closes #420 
connect to #440 
closes #440
=> Feature/nav menu item select #420
